a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
Addition = a + b
Subtraction = a - b
Multiplication = a * b
Division = a / b
print("Addtion = ", Addition)
print("Subtraction = ",Subtraction)
print("Multiplication = ", Multiplication)
print("Division = ", Division)